const express = require("express");
const router = express.Router();
const authRoutes = require("./auth.routes");
const taskRoutes = require("./task.routes");
const userRoutes = require("./user.routes");
const authMiddleware = require("../../middleware/auth.middleware");
router.use("/auth", authRoutes);
router.use("/tasks", authMiddleware, taskRoutes);
router.use("/user", authMiddleware, userRoutes);
module.exports = router;
